# Generated by Django 4.2.7 on 2023-12-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('isSend', models.BooleanField(default=False)),
            ],
        ),
    ]
