# Generated by Django 4.2.7 on 2023-12-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='tittle',
            new_name='title',
        ),
    ]
